# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=30, unique=True)),
                ('fecha_registro', models.DateField()),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_TRANSITO', 'En tránsito'), ('EN_ADUANA', 'En aduana'), ('LIBERADA', 'Liberada'), ('CANCELADA', 'Cancelada')], default='REGISTRADA', max_length=20)),
                ('valor_fob', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_flete', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_seguro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_cif', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ruta_ingreso', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operación de importación',
                'verbose_name_plural': 'Operaciones de importación',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario_fob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_importacion', to='catalogo.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de importación',
                'verbose_name_plural': 'Detalles de importación',
            },
        ),
    ]
