# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importaciones', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionimportacion',
            name='agente_aduanal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_importacion', to='terceros.agenteaduanal'),
        ),
        migrations.AddField(
            model_name='operacionimportacion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_importacion', to='terceros.proveedor'),
        ),
        migrations.AddField(
            model_name='operacionimportacion',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_importacion', to='terceros.transportista'),
        ),
        migrations.AddField(
            model_name='detalleimportacion',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='importaciones.operacionimportacion'),
        ),
        migrations.AddIndex(
            model_name='operacionimportacion',
            index=models.Index(fields=['estado'], name='importacion_estado_fd0de3_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionimportacion',
            index=models.Index(fields=['fecha_registro'], name='importacion_fecha_r_29b07f_idx'),
        ),
        migrations.AddConstraint(
            model_name='detalleimportacion',
            constraint=models.UniqueConstraint(fields=('operacion', 'variante'), name='unique_variante_por_operacion'),
        ),
    ]
