# Generated by Django 5.2.17 on 2026-08-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Costeo',
                'verbose_name_plural': 'Costeos',
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARANCEL', 'Arancel'), ('IVA', 'IVA')], max_length=10)),
                ('partida_arancelaria', models.CharField(blank=True, max_length=20)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Tributo',
                'verbose_name_plural': 'Tributos',
            },
        ),
    ]
