# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costeo', '0001_initial'),
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='operacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costeo', to='importaciones.operacionimportacion'),
        ),
        migrations.AddField(
            model_name='tributo',
            name='costeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos', to='costeo.costeo'),
        ),
    ]
