# Generated by Django 5.2.17 on 2026-09-02 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='tributo',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tributo',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
