# Generated by Django 5.2.17 on 2026-08-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('numero_registro', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Agente aduanal',
                'verbose_name_plural': 'Agentes aduanales',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ClienteMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_negocio', models.CharField(blank=True, max_length=100)),
                ('pedido_minimo_modelo', models.PositiveIntegerField(default=1, help_text='Cantidad mínima exigida por modelo (Prenda) en cada pedido de este cliente.')),
            ],
            options={
                'verbose_name': 'Cliente mayorista',
                'verbose_name_plural': 'Clientes mayoristas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fabrica', models.CharField(blank=True, max_length=255)),
                ('ciudad_origen', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='China', max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('MARITIMO', 'Marítimo'), ('AEREO', 'Aéreo'), ('TERRESTRE', 'Terrestre')], max_length=20)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'ordering': ['razon_social'],
            },
        ),
    ]
