# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemayorista',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de acceso al portal mayorista asociada a este cliente (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_mayorista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['razon_social'], name='terceros_pr_razon_s_463329_idx'),
        ),
        migrations.AddIndex(
            model_name='clientemayorista',
            index=models.Index(fields=['razon_social'], name='terceros_cl_razon_s_c38c4d_idx'),
        ),
    ]
