# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_repr', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(max_length=100)),
                ('entidad_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('entidad_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
