# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['fecha_hora'], name='auditoria_b_fecha_h_b77d28_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['accion'], name='auditoria_b_accion_bffca7_idx'),
        ),
    ]
