# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomayorista',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='terceros.clientemayorista'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedidomayorista'),
        ),
        migrations.AddIndex(
            model_name='pedidomayorista',
            index=models.Index(fields=['estado'], name='pedidos_ped_estado_67acee_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidomayorista',
            index=models.Index(fields=['fecha'], name='pedidos_ped_fecha_6c9416_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'variante'), name='unique_variante_por_pedido'),
        ),
    ]
