# Generated by Django 5.2.17 on 2026-08-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('BL', 'Bill of Lading'), ('PACKING_LIST', 'Packing list'), ('CERTIFICADO_ORIGEN', 'Certificado de origen'), ('OTRO', 'Otro')], max_length=25)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
