# Generated by Django 5.2.17 on 2026-08-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='importaciones.operacionimportacion'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo'], name='documentos__tipo_384b87_idx'),
        ),
    ]
